---
- name: Deploy ItemSim Server
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Check Docker service status
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: Check Docker Swarm status
      docker_swarm:
        state: present
        
    - name: Create deployment directory
      file:
        path: "{{ deploy_path }}"
        state: directory
        mode: '0755'
        
    - name: Create docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ deploy_path }}/docker-compose.yml"
        mode: '0644'
    
    - name: Create .env file
      template:
        src: templates/env.j2
        dest: "{{ deploy_path }}/.env"
        mode: '0644'
        
    - name: Deploy with Docker Swarm
      docker_stack:
        name: "{{ app_name }}"
        state: present
        compose:
          - "{{ deploy_path }}/docker-compose.yml"
        with_registry_auth: yes
